# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose

# version: "3.9"

# services:
#   app:
#     build:
#       context: .
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     volumes:
#       - .:/app
#     environment:
#       FLASK_ENV: development

#   db:
#     image: postgres:15
#     container_name: tasklist-db
#     environment:
#       POSTGRES_USER: taskuser
#       POSTGRES_PASSWORD: taskpass
#       POSTGRES_DB: taskdb
#     ports:
#       - "5432:5432"
#     volumes:
#       - db_data:/var/lib/postgresql/data

# volumes:
#   db_data:

version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
